Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [1]:
import pandas as pd
import numpy as np

In [3]:
#Load the patient dataset and show summary with info().
patients=pd.read_csv('Patient_Data.csv')

In [4]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [5]:
billing=pd.read_csv('Billing_Data.csv')

In [6]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [7]:
patients

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [8]:
# 5.Remove duplicate patient records based on PatientID.
patients.duplicated().sum()

np.int64(1)

In [9]:
patients.drop_duplicates(inplace=True,ignore_index=True)

In [10]:
patients.duplicated().sum()

np.int64(0)

In [11]:
patients

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [13]:
patients=patients.drop(columns=['ReceptionistID', 'CheckInTime'])

In [14]:
patients

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [29]:
dept_bill_summary=patients.groupby('Department')['BillAmount'].sum()
dept_bill_summary

Department
Cardiology     11200.000000
Dermatology     6233.333333
Neurology       6233.333333
Orthopedics     7500.000000
Name: BillAmount, dtype: float64

In [19]:
patients["BillAmount"]=patients["BillAmount"].fillna(patients["BillAmount"].mean())

In [20]:
merged = pd.merge(patients, billing, on="PatientID")

In [21]:
new_patients = pd.DataFrame({
    "PatientID": [2001, 2002],
    "Department": ["Cardiology", "Neurology"],
    "Doctor": ["Dr. Smith", "Dr. John"],
    "BillAmount": [5000, 7000],
    "Name": ["New Patient A", "New Patient B"],
    "InsuranceCovered": ["Yes", "No"],
    "FinalAmount": [4000, 7000]})

In [22]:
merged = pd.concat([merged, new_patients], ignore_index=True)

In [27]:
extra_col = pd.DataFrame({
    'DiscountApplied': ["Yes", "No"]*(len(merged)// 2 + 1),
    'PaymentStatus': ["Paid", "Pending"]*(len(merged)//2 + 1)
})
final_df = pd.concat([merged, extra_cols[:len(merged)]], axis=1)

In [31]:
dept_bill_summary,extra_col.head()

(Department
 Cardiology     11200.000000
 Dermatology     6233.333333
 Neurology       6233.333333
 Orthopedics     7500.000000
 Name: BillAmount, dtype: float64,
   DiscountApplied PaymentStatus
 0             Yes          Paid
 1              No       Pending
 2             Yes          Paid
 3              No       Pending
 4             Yes          Paid)